local loadingScreenTips = {
	"The colour of a tower's portal indicates it's difficulty",
	"Cheaty123457 was here",
	"One tower a day keeps something away",
	"loadingScreen.MainFrame.SillyText.Text = loadingScreenTips[math.random(1, #loadingScreenTips)],",
	"[Insert epic loading screen tip here]",
	"The stage is a lie",
	"This game was once called Goldfish's Trinity Towers (GTT)",
	"Need some cheese?",
	"Soul crushings are some of the hardest challenges you can face",
	"Five hundred (hundred) parts",
	"This is a tip, this is so useful",
	"Absolution Studios has its birthday on June 22!",
	":p",
	"Based off of EToH",
	"This game released on August 28, 2025",
}

return loadingScreenTips
