local module = {
	["ToIDLY"] = {
		Name = "Tower of I don't love you"
	},
	["ToAT"] = {
		Name = "Tower of Absolute Tranquility"
	},
	["ToTFiC"] = {
		Name = "Tower of The Fog is Coming"
	},
	["ToQE"] = {
		Name = "Tower of Quick Expression"
	},
	["ToCA"] = {
		Name = "Tower of Contrasting Areas"
	},
	["ToHS"] = {
		Name = "Tower of Head Slamming"
	},
	["ToWS"] = {
		Name = "Tower of Wacky Silly"
	},
	["ToDF"] = {
		Name = "Tower of Desk Flipping"
	},
	["ToNNT"] = {
		Name = "Tower of New Nail Tech"
	},
	["MToBVC"] = {
		Name = "Mini-Tower of Being Very Chub"
	},
	["ToISM"] = {
		Name = "Tower of Incredibly Scary Movement"
	},
}

return module
