-- A config module containing every tower rush in this realm.
-- More info in the manual @ 2.3.1 - Adding a tower rush.

return {
	IndustrialWastefieldTowerRush = {
		BadgeID = 0,
		Title = "Industrial Wastefield Tower Rush",
		Difficulty = "TowerRush",
		WinroomMarker = "",
		Towers = {
			"ToIDLY",
			"ToTT",
			"ToAT",
			"ToTFiC",
			"ToQE",
			"ToDF",
			"ToCA",
			"ToWS",
			"ToHS",
			"ToNNT",
		}
	},
}
